name: Docker CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t fastapi-app .

    - name: Run Docker Container
      run: |
        docker run -d --name fastapi-container -p 8000:8000 fastapi-app

    - name: Test API Endpoints
      run: |
        sleep 5 # Allow some time for the container to start
        curl -f http://localhost:8000/docs # Test FastAPI Swagger UI
        curl -f http://localhost:8000/clients # Test a sample endpoint

    - name: Cleanup
      run: |
        docker stop fastapi-container
        docker rm fastapi-container
